In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np
import plotnine as pn
import seaborn as sns
import matplotlib
import os
from pyhere import here
from janitor import clean_names

pd.set_option('display.max_columns', None)
pd.options.mode.copy_on_write = True
matplotlib.rcParams.update({'savefig.bbox': 'tight'})
pn.theme_set(pn.theme_light())

In [2]:
df = pd.read_csv(here('data/analytic_data2025_v3.csv'), skiprows = 1)

,statecode,countycode,fipscode,state,county,year,county_clustered,v001_rawvalue,v001_numerator,v001_denominator,v001_cilow,v001_cihigh,v001_flag,v001_race_aian,v001_race_aian_cilow,v001_race_aian_cihigh,v001_race_aian_flag,v001_race_asian,v001_race_asian_cilow,v001_race_asian_cihigh,v001_race_asian_flag,v001_race_black,v001_race_black_cilow,v001_race_black_cihigh,v001_race_black_flag,v001_race_hispanic,v001_race_hispanic_cilow,v001_race_hispanic_cihigh,v001_race_hispanic_flag,v001_race_white,v001_race_white_cilow,v001_race_white_cihigh,v001_race_white_flag,v001_race_nhopi,v001_race_nhopi_cilow,v001_race_nhopi_cihigh,v001_race_nhopi_flag,v001_race_tom_flag,v036_rawvalue,v036_numerator,v036_denominator,v036_cilow,v036_cihigh,v037_rawvalue,v037_numerator,v037_denominator,v037_cilow,v037_cihigh,v037_flag,v037_race_aian,v037_race_aian_cilow,v037_race_aian_cihigh,v037_race_asian,v037_race_asian_cilow,v037_race_asian_cihigh,v037_race_black,v037_race_black_cilow,v037_race_black_cihigh,v037_race_hispanic,v037_race_hispanic_cilow,v037_race_hispanic_cihigh,v037_race_white,v037_race_white_cilow,v037_race_white_cihigh,v037_race_nhopi,v037_race_nhopi_cilow,v037_race_nhopi_cihigh,v037_race_tom,v037_race_tom_cilow,v037_race_tom_cihigh,v042_rawvalue,v042_numerator,v042_denominator,v042_cilow,v042_cihigh,v002_rawvalue,v002_numerator,v002_denominator,v002_cilow,v002_cihigh,v155_rawvalue,v155_numerator,v155_denominator,v155_cilow,v155_cihigh,v155_race_aian,v155_race_asian,v155_race_black,v155_race_hispanic,v155_race_white,v132_rawvalue,v132_numerator,v132_denominator,v132_cilow,v132_cihigh,v133_rawvalue,v133_numerator,v133_denominator,v133_cilow,v133_cihigh,v004_rawvalue,v004_numerator,v004_denominator,v004_cilow,v004_cihigh,v004_other_data_1,v062_rawvalue,v062_numerator,v062_denominator,v062_cilow,v062_cihigh,v062_other_data_1,v088_rawvalue,v088_numerator,v088_denominator,v088_cilow,v088_cihigh,v088_other_data_1,v005_rawvalue,v005_numerator,v005_denominator,v005_cilow,v005_cihigh,v005_race_aian,v005_race_asian,v005_race_black,v005_race_hispanic,v005_race_white,v050_rawvalue,v050_numerator,v050_denominator,v050_cilow,v050_cihigh,v050_race_aian,v050_race_asian,v050_race_black,v050_race_hispanic,v050_race_white,v085_rawvalue,v085_numerator,v085_denominator,v085_cilow,v085_cihigh,v136_rawvalue,v136_numerator,v136_denominator,v136_cilow,v136_cihigh,v136_other_data_1,v136_other_data_1_cilow,v136_other_data_1_cihigh,v136_other_data_2,v136_other_data_2_cilow,v136_other_data_2_cihigh,v136_other_data_3,v136_other_data_3_cilow,v136_other_data_3_cihigh,v067_rawvalue,v067_numerator,v067_denominator,v067_cilow,v067_cihigh,v067_race_aian,v067_race_aian_cilow,v067_race_aian_cihigh,v067_race_asian,v067_race_asian_cilow,v067_race_asian_cihigh,v067_race_black,v067_race_black_cilow,v067_race_black_cihigh,v067_race_hispanic,v067_race_hispanic_cilow,v067_race_hispanic_cihigh,v067_race_white,v067_race_white_cilow,v067_race_white_cihigh,v137_rawvalue,v137_numerator,v137_denominator,v137_cilow,v137_cihigh,v125_rawvalue,v125_numerator,v125_denominator,v125_cilow,v125_cihigh,v124_rawvalue,v124_numerator,v124_denominator,v124_cilow,v124_cihigh,v166_rawvalue,v166_numerator,v166_denominator,v166_cilow,v166_cihigh,v181_rawvalue,v181_numerator,v181_denominator,v181_cilow,v181_cihigh,v069_rawvalue,v069_numerator,v069_denominator,v069_cilow,v069_cihigh,v168_rawvalue,v168_numerator,v168_denominator,v168_cilow,v168_cihigh,v023_rawvalue,v023_numerator,v023_denominator,v023_cilow,v023_cihigh,v044_rawvalue,v044_numerator,v044_denominator,v044_cilow,v044_cihigh,v024_rawvalue,v024_numerator,v024_denominator,v024_cilow,v024_cihigh,v024_race_aian,v024_race_aian_cilow,v024_race_aian_cihigh,v024_race_asian,v024_race_asian_cilow,v024_race_asian_cihigh,v024_race_black,v024_race_black_cilow,v024_race_black_cihigh,v024_race_hispanic,v024_race_hispanic_cilow,v024_race_hispanic_cihigh,v024_race_white,v024_race_white_cilow,v024_race_white_cihigh,v135_rawvalue,v135_numerator,v135_denominator,v135_cilow,v135_cihigh,v135_race_aian,v135_race_aian_cilow,v135_race_aian_cihigh,v135_race_asian,v135_race_asian_cilow,v135_race_asian_cihigh,v135_race_black,v135_race_black_cilow,v135_race_black_cihigh,v135_race_hispanic,v135_race_hispanic_cilow,v135_race_hispanic_cihigh,v135_race_white,v135_race_white_cilow,v135_race_white_cihigh,v135_race_nhopi,v135_race_nhopi_cilow,v135_race_nhopi_cihigh,v140_rawvalue,v140_numerator,v140_denominator,v140_cilow,v140_cihigh,v171_rawvalue,v171_numerator,v171_denominator,v171_cilow,v171_cihigh,v147_rawvalue,v147_numerator,v147_denominator,v147_cilow,v147_cihigh,v147_race_aian,v147_race_aian_cilow,v147_race_aian_cihigh,v147_race_asian,v147_race_asian_cilow,v147_race_asian_cihigh,v147_race_black,v147_race_black_cilow,v147_race_black_cihigh,v147_race_hispanic,v147_race_hispanic_cilow,v147_race_hispanic_cihigh,v147_race_white,v147_race_white_cilow,v147_race_white_cihigh,v147_race_nhopi,v147_race_nhopi_cilow,v147_race_nhopi_cihigh,v127_rawvalue,v127_numerator,v127_denominator,v127_cilow,v127_cihigh,v127_race_aian,v127_race_aian_cilow,v127_race_aian_cihigh,v127_race_asian,v127_race_asian_cilow,v127_race_asian_cihigh,v127_race_black,v127_race_black_cilow,v127_race_black_cihigh,v127_race_hispanic,v127_race_hispanic_cilow,v127_race_hispanic_cihigh,v127_race_white,v127_race_white_cilow,v127_race_white_cihigh,v127_race_nhopi,v127_race_nhopi_cilow,v127_race_nhopi_cihigh,v128_rawvalue,v128_numerator,v128_denominator,v128_cilow,v128_cihigh,v128_race_aian,v128_race_aian_cilow,v128_race_aian_cihigh,v128_race_asian,v128_race_asian_cilow,v128_race_asian_cihigh,v128_race_black,v128_race_black_cilow,v128_race_black_cihigh,v128_race_hispanic,v128_race_hispanic_cilow,v128_race_hispanic_cihigh,v128_race_white,v128_race_white_cilow,v128_race_white_cihigh,v128_race_nhopi,v128_race_nhopi_cilow,v128_race_nhopi_cihigh,v129_rawvalue,v129_numerator,v129_denominator,v129_cilow,v129_cihigh,v129_race_aian,v129_race_aian_cilow,v129_race_aian_cihigh,v129_race_asian,v129_race_asian_cilow,v129_race_asian_cihigh,v129_race_black,v129_race_black_cilow,v129_race_black_cihigh,v129_race_hispanic,v129_race_hispanic_cilow,v129_race_hispanic_cihigh,v129_race_white,v129_race_white_cilow,v129_race_white_cihigh,v129_race_nhopi,v129_race_nhopi_cilow,v129_race_nhopi_cihigh,v129_race_tom,v129_race_tom_cilow,v129_race_tom_cihigh,v144_rawvalue,v144_numerator,v144_denominator,v144_cilow,v144_cihigh,v060_rawvalue,v060_numerator,v060_denominator,v060_cilow,v060_cihigh,v061_rawvalue,v061_numerator,v061_denominator,v061_cilow,v061_cihigh,v011_rawvalue,v011_numerator,v011_denominator,v011_cilow,v011_cihigh,v145_rawvalue,v145_numerator,v145_denominator,v145_cilow,v145_cihigh,v161_rawvalue,v161_numerator,v161_denominator,v161_cilow,v161_cihigh,v161_other_data_1,v161_race_aian,v161_race_aian_cilow,v161_race_aian_cihigh,v161_race_asian,v161_race_asian_cilow,v161_race_asian_cihigh,v161_race_black,v161_race_black_cilow,v161_race_black_cihigh,v161_race_hispanic,v161_race_hispanic_cilow,v161_race_hispanic_cihigh,v161_race_white,v161_race_white_cilow,v161_race_white_cihigh,v161_race_nhopi,v161_race_nhopi_cilow,v161_race_nhopi_cihigh,v183_rawvalue,v183_numerator,v183_denominator,v183_cilow,v183_cihigh,v083_rawvalue,v083_numerator,v083_denominator,v083_cilow,v083_cihigh,v139_rawvalue,v139_numerator,v139_denominator,v139_cilow,v139_cihigh,v143_rawvalue,v143_numerator,v143_denominator,v143_cilow,v143_cihigh,v014_rawvalue,v014_numerator,v014_denominator,v014_cilow,v014_cihigh,v014_race_aian,v014_race_aian_cilow,v014_race_aian_cihigh,v014_race_asian,v014_race_asian_cilow,v014_race_asian_cihigh,v014_race_black,v014_race_black_cilow,v014_race_black_cihigh,v014_race_hispanic,v014_race_hispanic_cilow,v014_race_hispanic_cihigh,v014_race_white,v014_race_white_cilow,v014_race_white_cihigh,v014_race_nhopi,v014_race_nhopi_cilow,v014_race_nhopi_cihigh,v014_race_tom,v014_race_tom_cilow,v014_race_tom_cihigh,v045_rawvalue,v045_numerator,v045_denominator,v045_cilow,v045_cihigh,v049_rawvalue,v049_numerator,v049_denominator,v049_cilow,v049_cihigh,v134_rawvalue,v134_numerator,v134_denominator,v134_cilow,v134_cihigh,v138_rawvalue,v138_numerator,v138_denominator,v138_cilow,v138_cihigh,v138_race_aian,v138_race_aian_cilow,v138_race_aian_cihigh,v138_race_asian,v138_race_asian_cilow,v138_race_asian_cihigh,v138_race_black,v138_race_black_cilow,v138_race_black_cihigh,v138_race_hispanic,v138_race_hispanic_cilow,v138_race_hispanic_cihigh,v138_race_white,v138_race_white_cilow,v138_race_white_cihigh,v138_race_nhopi,v138_race_nhopi_cilow,v138_race_nhopi_cihigh,v009_rawvalue,v009_numerator,v009_denominator,v009_cilow,v009_cihigh,v070_rawvalue,v070_numerator,v070_denominator,v070_cilow,v070_cihigh,v003_rawvalue,v003_numerator,v003_denominator,v003_cilow,v003_cihigh,v122_rawvalue,v122_numerator,v122_denominator,v122_cilow,v122_cihigh,v131_rawvalue,v131_numerator,v131_denominator,v131_cilow,v131_cihigh,v131_other_data_1,v156_rawvalue,v156_numerator,v156_denominator,v156_cilow,v156_cihigh,v153_rawvalue,v153_numerator,v153_denominator,v153_cilow,v153_cihigh,v154_rawvalue,v154_numerator,v154_denominator,v154_cilow,v154_cihigh,v179_rawvalue,v179_numerator,v179_denominator,v179_cilow,v179_cihigh,v182_rawvalue,v182_numerator,v182_denominator,v182_cilow,v182_cihigh,v182_other_data_1,v182_other_data_2,v182_other_data_3,v178_rawvalue,v178_numerator,v178_denominator,v178_cilow,v178_cihigh,v177_rawvalue,v177_numerator,v177_denominator,v177_cilow,v177_cihigh,v021_rawvalue,v021_numerator,v021_denominator,v021_cilow,v021_cihigh,v159_rawvalue,v159_numerator,v159_denominator,v159_cilow,v159_cihigh,v159_race_aian,v159_race_asian,v159_race_black,v159_race_hispanic,v159_race_white,v160_rawvalue,v160_numerator,v160_denominator,v160_cilow,v160_cihigh,v160_race_aian,v160_race_asian,v160_race_black,v160_race_hispanic,v160_race_white,v167_rawvalue,v167_numerator,v167_denominator,v167_cilow,v167_cihigh,v169_rawvalue,v169_numerator,v169_denominator,v169_cilow,v169_cihigh,v065_rawvalue,v065_numerator,v065_denominator,v065_cilow,v065_cihigh,v151_rawvalue,v151_numerator,v151_denominator,v151_cilow,v151_cihigh,v063_rawvalue,v063_numerator,v063_denominator,v063_cilow,v063_cihigh,v063_race_aian,v063_race_aian_cilow,v063_race_aian_cihigh,v063_race_asian,v063_race_asian_cilow,v063_race_asian_cihigh,v063_race_black,v063_race_black_cilow,v063_race_black_cihigh,v063_race_hispanic,v063_race_hispanic_cilow,v063_race_hispanic_cihigh,v063_race_white,v063_race_white_cilow,v063_race_white_cihigh,v170_rawvalue,v170_numerator,v170_denominator,v170_cilow,v170_cihigh,v172_rawvalue,v172_numerator,v172_denominator,v172_cilow,v172_cihigh,v141_rawvalue,v141_numerator,v141_denominator,v141_cilow,v141_cihigh,v015_rawvalue,v015_numerator,v015_denominator,v015_cilow,v015_cihigh,v015_race_aian,v015_race_aian_cilow,v015_race_aian_cihigh,v015_race_asian,v015_race_asian_cilow,v015_race_asian_cihigh,v015_race_black,v015_race_black_cilow,v015_race_black_cihigh,v015_race_hispanic,v015_race_hispanic_cilow,v015_race_hispanic_cihigh,v015_race_white,v015_race_white_cilow,v015_race_white_cihigh,v015_race_nhopi,v015_race_nhopi_cilow,v015_race_nhopi_cihigh,v039_rawvalue,v039_numerator,v039_denominator,v039_cilow,v039_cihigh,v039_race_aian,v039_race_aian_cilow,v039_race_aian_cihigh,v039_race_asian,v039_race_asian_cilow,v039_race_asian_cihigh,v039_race_black,v039_race_black_cilow,v039_race_black_cihigh,v039_race_hispanic,v039_race_hispanic_cilow,v039_race_hispanic_cihigh,v039_race_white,v039_race_white_cilow,v039_race_white_cihigh,v039_race_nhopi,v039_race_nhopi_cilow,v039_race_nhopi_cihigh,v148_rawvalue,v148_numerator,v148_denominator,v148_cilow,v148_cihigh,v148_race_aian,v148_race_aian_cilow,v148_race_aian_cihigh,v148_race_asian,v148_race_asian_cilow,v148_race_asian_cihigh,v148_race_black,v148_race_black_cilow,v148_race_black_cihigh,v148_race_hispanic,v148_race_hispanic_cilow,v148_race_hispanic_cihigh,v148_race_white,v148_race_white_cilow,v148_race_white_cihigh,v148_race_nhopi,v148_race_nhopi_cilow,v148_race_nhopi_cihigh,v149_rawvalue,v149_numerator,v149_denominator,v149_cilow,v149_cihigh,v184_rawvalue,v184_numerator,v184_denominator,v184_cilow,v184_cihigh,v052_rawvalue,v052_numerator,v052_denominator,v052_cilow,v052_cihigh,v053_rawvalue,v053_numerator,v053_denominator,v053_cilow,v053_cihigh,v057_rawvalue,v057_numerator,v057_denominator,v057_cilow,v057_cihigh,v055_rawvalue,v055_numerator,v055_denominator,v055_cilow,v055_cihigh,v081_rawvalue,v081_numerator,v081_denominator,v081_cilow,v081_cihigh,v056_rawvalue,v056_numerator,v056_denominator,v056_cilow,v056_cihigh,v080_rawvalue,v080_numerator,v080_denominator,v080_cilow,v080_cihigh,v054_rawvalue,v054_numerator,v054_denominator,v054_cilow,v054_cihigh,v126_rawvalue,v126_numerator,v126_denominator,v126_cilow,v126_cihigh,v180_rawvalue,v180_numerator,v180_denominator,v180_cilow,v180_cihigh,v059_rawvalue,v059_numerator,v059_denominator,v059_cilow,v059_cihigh,v082_rawvalue,v082_numerator,v082_denominator,v082_cilow,v082_cihigh,v058_rawvalue,v058_numerator,v058_denominator,v058_cilow,v058_cihigh,v051_rawvalue,v051_numerator,v051_denominator,v051_cilow,v051_cihigh
0,0,0,0,US,United States,2025,NaN,8351.736549,4763989.0,925367214.0,8340.503474,8362.969624,0,17595.989732,17402.762062,17789.217401,NaN,3287.232515,3259.027426,3315.437604,NaN,13698.397493,13657.966915,13738.828072,NaN,6933.658715,6911.042622,6956.274808,NaN,8038.489963,8023.909547,8053.070379,NaN,12223.375848,11925.855871,12520.895824,NaN,NaN,3.935528,NaN,NaN,3.881278,3.989778,0.084005,2176957.0,25914651.0,0.083898,0.084112,0,0.082429,0.081194,0.083664,0.088945,0.088503,0.089387,0.143451,0.143094,0.143808,0.076459,0.076252,0.076667,0.069749,0.069612,0.069886,0.085545,0.083443,0.087647,0.091163,0.090434,0.091892,5.149831,NaN,NaN,5.089778,5.209884,0.173,NaN,NaN,0.170,0.175,0.48,NaN,NaN,NaN,NaN,0.37,0.49,0.36,0.33,0.50,0.844524,279916955.0,331449281.0,NaN,NaN,7.4,0.061002,0.135,NaN,NaN,0.000749,248730.0,331893745.0,NaN,NaN,1334.353496,0.003325,1113571.0,334914895.0,NaN,NaN,300.757558,0.000735,244838.0,333287557.0,NaN,NaN,1361.257472,2666.0,NaN,NaN,NaN,NaN,4000.0,1576.0,4268.0,2758.0,2529.0,0.44,NaN,NaN,NaN,NaN,0.29,0.34,0.40,0.30,0.46,0.095484,25694722.0,269100387.0,NaN,NaN,0.168447,20889310.0,124010995.0,NaN,NaN,0.136146,NaN,NaN,0.033343,NaN,NaN,0.009751,NaN,NaN,0.701914,110653318.0,157645183.0,0.700758,0.703070,0.681120,NaN,NaN,0.578531,NaN,NaN,0.683894,NaN,NaN,0.679086,NaN,NaN,0.727782,NaN,NaN,0.365,NaN,157645183.0,0.362617,0.367383,7.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.897119,114367262.0,127482865.0,0.895173,0.899064,2.060697,656555027.0,318608226.0,2.060539,2.060855,0.678254,60358208.0,88990519.0,0.676933,0.679575,0.893929,204204444.0,228434661.0,0.893120,0.894739,0.036391,6065991.0,166689795.0,NaN,NaN,4.888713,157573.0,32232.0,4.871260,4.906167,0.160,11445264.0,NaN,0.157617,0.162383,0.279623,0.274810,0.284435,0.106021,0.104055,0.107986,0.301747,0.299193,0.304301,0.222560,0.220566,0.224554,0.100266,0.099158,0.101375,83.562395,1378840.0,1.650072e+09,83.422916,83.701874,146.502099,144.350527,148.65367,26.833760,26.507704,27.159816,107.919702,107.472611,108.366792,52.142666,51.887673,52.397660,94.400058,94.208150,94.591966,63.899331,61.066047,66.732615,9.091519,303009.0,333287557.0,NaN,NaN,0.278857,NaN,NaN,NaN,NaN,77.099412,NaN,NaN,77.089616,77.109208,71.763258,71.609194,71.917321,86.047160,85.992153,86.102168,72.102748,72.072319,72.133176,79.729744,79.699189,79.760299,77.187405,77.175315,77.199495,76.417912,76.046783,76.789041,406.585700,4763989.0,925367214.0,406.207739,406.963662,715.721176,709.514361,721.927992,174.250961,173.230337,175.271586,631.227174,629.854531,632.599818,338.014218,337.098970,338.929467,398.763522,398.291593,399.235452,562.691667,551.813144,573.570190,51.574089,168175.0,326084286.0,51.327595,51.820583,87.766693,84.203703,91.329684,27.123983,26.352125,27.895840,102.393474,101.457584,103.329365,44.881401,44.426368,45.336435,43.675501,43.354051,43.996950,81.905572,75.133816,88.677329,5.627984,147939.0,26286324.0,5.599304,5.656663,8.061374,7.665499,8.457248,2.833357,2.751769,2.914945,11.259785,11.152792,11.366779,5.123458,5.067475,5.179442,4.438764,4.403215,4.474314,7.623378,6.963681,8.283076,8.677043,8.439571,8.914514,0.122,NaN,NaN,0.119,0.124,0.100,NaN,NaN,NaN,NaN,386.6,1092023.0,NaN,NaN,NaN,0.335,NaN,NaN,0.332,0.338,0.163,NaN,NaN,0.161,0.166,13.987736,239283.0,1.650072e+09,13.930439,14.045034,14.501364,24.770372,23.872761,25.667983,6.680799,6.520215,6.841382,8.036544,7.913702,8.159387,7.640746,7.540099,7.741394,17.522158,17.438376,17.605941,13.120447,11.852327,14.388567,0.330,NaN,NaN,0.326,0.334,0.061002,1.883408e+07,308745538.0,NaN,NaN,0.135,44151000.0,NaN,NaN,NaN,0.368,NaN,NaN,0.365,0.371,15.536374,1135704.0,73099680.0,15.507800,15.564949,26.111611,25.707550,26.515672,2.182295,2.135981,2.228610,23.475345,23.380914,23.569777,23.835526,23.763917,23.907135,10.465876,10.433232,10.498521,22.740365,21.966355,23.514374,15.649379,15.501044,15.797714,495.0,1649716.0,NaN,NaN,NaN,0.193519,NaN,NaN,0.190737,0.196333,0.260942,51388.0,196933.0,0.259837,0.262048,30.808249,306439.0,994665425.0,30.699167,30.917330,53.523327,51.845641,55.201013,5.137443,4.955055,5.319831,44.028883,43.661557,44.396209,20.105608,19.902714,20.308502,33.976918,33.828158,34.125677,18.020122,16.098998,19.941246,0.132,NaN,NaN,0.130,0.135,0.232,NaN,NaN,0.229,0.235,0.112389,22237154.0,197858423.0,NaN,NaN,0.050782,3806126.0,74950230.0,NaN,NaN,0.001400,468761.0,334914895.0,NaN,NaN,714.468343,107.616657,NaN,NaN,NaN,NaN,0.650221,82892037.0,127482865.0,0.647102,0.653340,0.147124,18201241.0,123713841.0,0.146426,0.147822,0.509125,168749265.0,331449281.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.652,NaN,NaN,NaN,NaN,0.679095,158528503.0,233440760.0,NaN,NaN,0.870000,NaN,NaN,NaN,NaN,3.050059,NaN,NaN,NaN,NaN,2.811393,3.403940,2.546147,2.696537,3.256184,3.027575,NaN,NaN,NaN,NaN,2.696109,3.579931,2.432230,2.611213,3.251291,0.241396,NaN,NaN,NaN,NaN,1411.080,NaN,NaN,NaN,NaN,0.546069,24640047.0,45122591.0,NaN,NaN,0.813916,53445.0,65664.0,0.810572,0.817261,77719.0,NaN,NaN,77497.382979,77940.617021,59393.0,58830.617021,59955.382979,113106.0,112593.659570,113618.340430,53444.0,53205.702128,53682.297872,68890.0,68562.340426,69217.659574,84745.0,84567.468085,84922.531915,NaN,NaN,NaN,NaN,NaN,6.863867,NaN,NaN,NaN,NaN,62.505268,NaN,NaN,NaN,NaN,6.544597,150455.0,2.298919e+09,6.511527,6.577668,12.284477,11.756795,12.812159,1.522121,1.455840,1.588401,27.469438,27.278115,27.660761,5.903621,5.830526,5.976715,2.870344,2.842081,2.898607,7.020607,6.219446,7.821768,12.337494,283629.0,2.298919e+09,12.292088,12.382899,28.817189,28.008987,29.625391,4.430378,4.317299,4.543456,16.530364,16.381947,16.678781,11.027709,10.927809,11.127609,12.634324,12.575028,12.693619,11.399562,10.378677,12.420446,13.434683,221682.0,1.650072e+09,13.378757,13.490610,17.618747,16.872605,18.364888,2.763922,2.659278,2.868566,30.599878,30.361807,30.837948,8.004395,7.904488,8.104302,12.759663,12.689108,12.830218,9.77784,8.669525,10.886156,0.068181,1187439.0,17415920.0,0.067467,0.068895,0.251,NaN,NaN,NaN,NaN,0.217464,72831861.0,334914895.0,NaN,NaN,0.176906,59248361.0,334914895.0,NaN,NaN,0.505100,169165495.0,334914895.0,NaN,NaN,0.013396,4486417.0,334914895.0,NaN,NaN,0.063858,21386914.0,334914895.0,NaN,NaN,0.194733,65219145.0,334914895.0,NaN,NaN,0.002687,899815.0,334914895.0,NaN,NaN,0.126340,42313088.0,334914895.0,NaN,NaN,0.583529,195432584.0,334914895.0,NaN,NaN,0.287,NaN,NaN,0.284,0.290,0.041902,13134090.0,313447641.0,0.041633,0.042171,0.248337,18244481.0,73466592.0,0.246564,0.250110,0.200031,66300254.0,331449281.0,NaN,NaN,334914895.0,NaN,NaN,NaN,NaN

In [41]:
url = 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json'
import requests

response = requests.get(url)
mapp = response.json()
mapp['features'][0]

{'type': 'Feature',
 'properties': {'GEO_ID': '0500000US01001',
  'STATE': '01',
  'COUNTY': '001',
  'NAME': 'Autauga',
  'LSAD': 'County',
  'CENSUSAREA': 594.436},
 'geometry': {'type': 'Polygon',
  'coordinates': [[[-86.496774, 32.344437],
    [-86.717897, 32.402814],
    [-86.814912, 32.340803],
    [-86.890581, 32.502974],
    [-86.917595, 32.664169],
    [-86.71339, 32.661732],
    [-86.714219, 32.705694],
    [-86.413116, 32.707386],
    [-86.411172, 32.409937],
    [-86.496774, 32.344437]]]},
 'id': '01001'}

In [76]:
map_df = pd.json_normalize(mapp['features'],
                  record_path = None,
                  meta = ['type',
                          ['properties', 'GEO_ID'],
                          ['properties', 'STATE'],
                          ['properties', 'COUNTY'],
                          ['properties', 'NAME'],
                          ['properties', 'LSAD'],
                          ['properties', 'CENSUSAREA'],
                          ['geometry', 'type'],
                          ['geometry', 'coordinates'],
                          'id'
                          ]).clean_names(case_type = 'snake')

map_df = map_df.rename(columns = {'properties_geo_id': 'geo_id',
                         'properties_state': 'statecode',
                         'properties_county': 'county_code',
                         'properties_name': 'county',
                         'properties_lsad': 'county_type',
                         'properties_censusarea': 'census_area',
                         'geometry_coordinates': 'coordinates'
                         })

county_df = map_df.loc[map_df['county_type'] == 'County']
county_df = county_df.drop(columns = ['type', 'county_type'])
county_df.head()

,id,geo_id,statecode,county_code,county,census_area,geometry_type,coordinates
0,01001,0500000US01001,01,001,Autauga,594.436,Polygon,"[[[-86.496774, 32.344437], [-86.717897, 32.402..."
1,01009,0500000US01009,01,009,Blount,644.776,Polygon,"[[[-86.577799, 33.765316], [-86.759144, 33.840..."
2,01017,0500000US01017,01,017,Chambers,596.531,Polygon,"[[[-85.184131, 32.870525], [-85.123421, 32.772..."
3,01021,0500000US01021,01,021,Chilton,692.854,Polygon,"[[[-86.517344, 33.020566], [-86.515959, 32.929..."
4,01033,0500000US01033,01,033,Colbert,592.619,Polygon,"[[[-88.139988, 34.581703], [-88.139246, 34.587..."

In [ ]:
columns = df.loc[:, 'statecode':'year'].columns.tolist()
columns = columns + ['v011_rawvalue']

df = df.loc[:, columns].rename(columns = {'v011_rawvalue': 'adult_obesity'})

In [86]:
county_df[['id', 'statecode', 'county_code']] = county_df[['id', 'statecode', 'county_code']].astype(int)
county_df['census_area'] = county_df['census_area'].astype(float)

In [94]:
df.loc[df['statecode'] == 1, 'county']
df['county_drop'] = df['county'].str.replace(' County', '')
df = df.rename(columns = {'county': 'county_drop',
                     'county_drop': 'county'})

In [87]:
df.loc[df['county'].str.contains('Autauga')].merge(county_df.loc[county_df['county'] == 'Autauga'], how = 'outer')

,statecode,countycode,fipscode,state,county,year,adult_obesity,id,geo_id,county_code,census_area,geometry_type,coordinates
0,1,NaN,NaN,NaN,Autauga,NaN,NaN,1001.0,0500000US01001,1.0,594.436,Polygon,"[[[-86.496774, 32.344437], [-86.717897, 32.402..."
1,1,1.0,1001.0,AL,Autauga County,2025.0,0.384,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
merged = pd.merge(df, county_df.rename(columns={'state_code': 'statecode'}), how='left', on=['statecode', 'county'])

In [97]:
merged.head()

,statecode,countycode,fipscode,state,county_drop,year,adult_obesity,county,id,geo_id,county_code,census_area,geometry_type,coordinates
0,0,0,0,US,United States,2025,0.335,United States,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,1000,AL,Alabama,2025,0.384,Alabama,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,1001,AL,Autauga County,2025,0.384,Autauga,1001.0,0500000US01001,1.0,594.436,Polygon,"[[[-86.496774, 32.344437], [-86.717897, 32.402..."
3,1,3,1003,AL,Baldwin County,2025,0.368,Baldwin,1003.0,0500000US01003,3.0,1589.784,Polygon,"[[[-87.598927, 30.997454], [-87.594111, 30.976..."
4,1,5,1005,AL,Barbour County,2025,0.438,Barbour,1005.0,0500000US01005,5.0,884.876,Polygon,"[[[-85.056029, 32.063055], [-85.050212, 32.024..."

In [ ]:
from shapely.geometry import Polygon

# left off here
merged = gpd.GeoDataFrame(
    merged,
    geometry = merged['coordinates'].apply(lambda x: Polygon(x[0])),
    crs = 'EPSG:4326'  # WGS84 (lon/lat)
)

TypeError: 'float' object is not subscriptable